sudo: required
dist: trusty
language: python
python: "3.5"
install:
  - "sudo pip install ansible"
script:
  - "echo 'localhost' > tools/hosts"
  - "cd tools && ansible-playbook -i hosts -e 'mode=travis' --connection=local site.yml"
  - "make all test"
notifications:
  email:
    - james@overton.ca
#   - cjmungall@lbl.gov
#   - sjcarbon@lbl.gov
