# PURL configuration for http://purl.obolibrary.org/obo/aero

id: AERO
base_url: /obo/aero

base_redirect: http://code.google.com/p/adverse-event-reporting-ontology/

products:
- aero.owl: http://adverse-event-reporting-ontology.googlecode.com/svn/trunk/src/ontology/aero.owl

term_browser: ontobee
example_terms:
- AERO_0000001

entries:
- exact: /external.owl
  replacement: http://adverse-event-reporting-ontology.googlecode.com/svn/trunk/src/ontology/external.owl

- exact: /externalDerived.owl
  replacement: http://adverse-event-reporting-ontology.googlecode.com/svn/trunk/src/ontology/externalDerived.owl

- exact: /external-by-hand.owl
  replacement: http://adverse-event-reporting-ontology.googlecode.com/svn/trunk/src/ontology/external-by-hand.owl

- exact: /tracker
  replacement: http://code.google.com/p/adverse-event-reporting-ontology/issues/list

- exact: /OMRE_AEROImport.owl
  replacement: http://ogms.googlecode.com/svn/trunk/src/ontology/omre/OMRE_AEROImport.owl

- prefix: /about/
  replacement: http://www.ontobee.org/browser/rdf.php?o=AERO&iri=http://purl.obolibrary.org/obo/
  tests:
  - from: /about/AERO_0000001
    to: http://www.ontobee.org/browser/rdf.php?o=AERO&iri=http://purl.obolibrary.org/obo/AERO_0000001

