# PURL configuration for http://purl.obolibrary.org/obo/bspo

idspace: BSPO
base_url: /obo/bspo

products:
- pato.owl: https://raw.githubusercontent.com/obophenotype/bspo/master/pato.owl
- pato.obo: https://raw.githubusercontent.com/obophenotype/bspo/master/pato.obo

term_browser: ontobee
example_terms:
- BSPO_0000000

entries:
- prefix: /releases/
  replacement: https://raw.githubusercontent.com/obophenotype/bspo/v
