# PURL configuration for http://purl.obolibrary.org/obo/chmo

idspace: CHMO
base_url: /obo/chmo

products:
- chmo.owl: http://github.com/rsc-ontologies/rsc-cmo/chmo.owl
- chmo.obo: http://github.com/rsc-ontologies/rsc-cmo/chmo.obo

term_browser: ontobee
example_terms:
- CHMO_0002748
