# PURL configuration for http://purl.obolibrary.org/obo/clo

idspace: CLO
base_url: /obo/clo

products:
- clo.owl: https://raw.githubusercontent.com/CLO-ontology/CLO/master/src/ontology/clo.owl

term_browser: ontobee
example_terms:
- CLO_0000000
