# PURL configuration for http://purl.obolibrary.org/obo/cvdo

id: CVDO
base_url: /obo/cvdo

products:
- cvdo.owl: https://cvdo.googlecode.com/svn/trunk/src/ontology/core/cvdo.owl

term_browser: ontobee
example_terms:
- CVDO_0000010
