# PURL configuration for http://purl.obolibrary.org/obo/ddpheno

idspace: DDPHENO
base_url: /obo/ddpheno

products:
- ddpheno.owl: http://ontologies.berkeleybop.org/ddpheno.owl

term_browser: ontobee
example_terms:
- DDPHENO_0000001
