# PURL configuration for http://purl.obolibrary.org/obo/ddpheno

id: DDPHENO
base_url: /obo/ddpheno

products:
- ddpheno.owl: http://www.berkeleybop.org/ontologies/ddpheno.owl

term_browser: ontobee
example_terms:
- DDPHENO_0000001
