# PURL configuration for http://purl.obolibrary.org/obo/doid

idspace: DOID
base_url: /obo/doid

base_redirect: https://github.com/DiseaseOntology/HumanDiseaseOntology/tree/master/

products:
- doid.owl: http://ontologies.berkeleybop.org/doid.owl
- doid.obo: http://ontologies.berkeleybop.org/doid.obo

term_browser: ontobee
example_terms:
- DOID_4
