# PURL configuration for http://purl.obolibrary.org/obo/emapa

idspace: EMAPA
base_url: /obo/emapa

products:
- emapa.owl: https://raw.githubusercontent.com/obophenotype/mouse-anatomy-ontology/master/emapa.owl
- emapa.obo: https://raw.githubusercontent.com/obophenotype/mouse-anatomy-ontology/master/emapa.obo

term_browser: ontobee
example_terms:
- EMAPA_36040
