# PURL configuration for http://purl.obolibrary.org/obo/emap

id: EMAP
base_url: /obo/emap

products:
- emap.owl: http://www.berkeleybop.org/ontologies/emap.owl

term_browser: ontobee
example_terms:
- EMAP_1
