# PURL configuration for http://purl.obolibrary.org/obo/eo

idspace: EO
base_url: /obo/eo

products:
- eo.owl: http://www.berkeleybop.org/ontologies/eo.owl

term_browser: ontobee
example_terms:
- EO_0007359

entries:
- exact: /tracker
  replacement: https://sourceforge.net/tracker/?atid=5010796&group_id=76834&func=browse
