# PURL configuration for http://purl.obolibrary.org/obo/eupath

idspace: EUPATH
base_url: /obo/eupath

products:
- eupath.owl: https://raw.githubusercontent.com/EuPath-ontology/EuPath-ontology/master/ontology/src/eupath.owl

term_browser: ontobee
example_terms:
- EUPATH_0000001
