# PURL configuration for http://purl.obolibrary.org/obo/fao

idspace: FAO
base_url: /obo/fao

products:
- fao.owl: http://www.berkeleybop.org/ontologies/fao.owl

term_browser: ontobee
example_terms:
- FAO_0000001
