# PURL configuration for http://purl.obolibrary.org/obo/fma

idspace: FMA
base_url: /obo/fma

products:
- fma.owl: http://www.berkeleybop.org/ontologies/fma.owl
- fma.obo: http://www.berkeleybop.org/ontologies/fma.obo

term_browser: ontobee
example_terms:
- FMA_62955
