# PURL configuration for http://purl.obolibrary.org/obo/fypo

idspace: FYPO
base_url: /obo/fypo

products:
- fypo.owl: https://raw.githubusercontent.com/pombase/fypo/master/release/fypo.owl
- fypo.obo: https://raw.githubusercontent.com/pombase/fypo/master/release/fypo.obo

term_browser: ontobee
example_terms:
- FYPO_0000001
