# PURL configuration for http://purl.obolibrary.org/obo/hom

idspace: HOM
base_url: /obo/hom

products:
- hom.owl: http://www.berkeleybop.org/ontologies/hom.owl

term_browser: ontobee
example_terms:
- HOM_0000000
