# PURL configuration for http://purl.obolibrary.org/obo/imr

idspace: IMR
base_url: /obo/imr

products:
- imr.owl: http://www.berkeleybop.org/ontologies/imr.owl
- imr.obo: http://www.berkeleybop.org/ontologies/imr.obo

term_browser: ontobee
example_terms:
- IMR_0000001
