# PURL configuration for http://purl.obolibrary.org/obo/labo

idspace: LABO
base_url: /obo/labo

products:
- labo.owl: https://github.com/OpenLHS/LABO/blob/master/LABO.owl

term_browser: ontobee
example_terms:
- LABO_0000007
