# PURL configuration for http://purl.obolibrary.org/obo/miapa

idspace: MIAPA
base_url: /obo/miapa

products:
- miapa.owl: https://raw.githubusercontent.com/miapa/miapa/master/ontology/miapa.owl

term_browser: ontobee
example_terms:
- MIAPA_0000038
