# PURL configuration for http://purl.obolibrary.org/obo/micro

idspace: MICRO
base_url: /obo/micro

products:
- micro.owl: https://raw.githubusercontent.com/carrineblank/MicrO/master/MicrOandImportModules/MicrO.Oct15.owl

term_browser: ontobee
