# PURL configuration for http://purl.obolibrary.org/obo/mmusdv

idspace: MmusDv
base_url: /obo/mmusdv

products:
- mmusdv.owl: http://www.berkeleybop.org/ontologies/mmusdv.owl
- mmusdv.obo: http://www.berkeleybop.org/ontologies/mmusdv.obo

term_browser: ontobee
example_terms:
- MmusDv_0000000
