# PURL configuration for http://purl.obolibrary.org/obo/mop

idspace: MOP
base_url: /obo/mop

products:
- mop.owl: http://github.com/rsc-ontologies/rxno/mop.owl
- mop.obo: http://github.com/rsc-ontologies/rxno/mop.obo

term_browser: ontobee
example_terms:
- MOP_0000000
