# PURL configuration for http://purl.obolibrary.org/obo/ms

id: MS
base_url: /obo/ms

products:
- ms.owl: http://www.berkeleybop.org/ontologies/ms.owl
- ms.obo: http://www.berkeleybop.org/ontologies/ms.obo

term_browser: ontobee
example_terms:
- MS_0000000
