# PURL configuration for http://purl.obolibrary.org/obo/nbo

idspace: NBO
base_url: /obo/nbo

products:
- nbo.owl: https://raw.github.com/obo-behavior/behavior-ontology/master/nbo.owl

term_browser: ontobee
example_terms:
- NBO_0000607
