# PURL configuration for http://purl.obolibrary.org/obo/ncit

idspace: NCIT
base_url: /obo/ncit

products:
- ncit.owl: https://stars.renci.org/var/NCIt/ncit.owl
- ncit.obo: https://stars.renci.org/var/NCIt/ncit.obo

term_browser: ontobee

entries:
- prefix: /releases/
  replacement: https://stars.renci.org/var/NCIt/releases/

- prefix: /tracker/
  replacement: https://github.com/NCI-Thesaurus/thesaurus-obo-edition/issues

- prefix: /about/
  replacement: http://www.ontobee.org/ontology/NCIT?iri=http://purl.obolibrary.org/obo/

## generic fall-through, serve direct from github by default
- prefix: /
  replacement: https://raw.githubusercontent.com/NCI-Thesaurus/thesaurus-obo-edition/master/
