# PURL configuration for http://purl.obolibrary.org/obo/ncro

idspace: NCRO
base_url: /obo/ncro

products:
- ncro.owl: http://raw.githubusercontent.com/OmniSearch/ncro/master/src/ontology/ncro.owl
- ncro/imports.owl http://raw.githubusercontent.com/OmniSearch/ncro/master/src/ontology/imports.owl
- ncro/dev/ncro.owl http://raw.githubusercontent.com/OmniSearch/ncro/master/src/ontology/ncro.owl
- ncro/dev/ncro/imports.owl http://raw.githubusercontent.com/OmniSearch/ncro/master/src/ontology/imports.owl
# - ncro.obo: http://www.berkeleybop.org/ontologies/doid.obo

term_browser: ontobee
example_terms:
- NCRO_0000818
