# PURL configuration for http://purl.obolibrary.org/obo/oba

idspace: OBA
base_url: /obo/oba

products:
- oba.owl: http://www.berkeleybop.org/ontologies/oba.owl

term_browser: ontobee
example_terms:
- OBA_0000001
