# PURL configuration for OBI

purl_rules:

### Top-level Rules

- term_browser: ontobee
  tests:
  - path: /obo/OBI_0000070
    replacement: http://www.ontobee.org/browser/rdf.php?o=OBI&iri=http://purl.obolibrary.org/obo/OBI_0000070

- path: /obo/obi.owl
  replacement: /obo/obi/2015-10-20/obi.owl

- path: /obo/obi.obo
  replacement: http://www.berkeleybop.org/ontologies/obi.obo

### Current Releases

- path: /obo/obi/obi_core.owl
  replacement: http://svn.code.sf.net/p/obi/code/releases/2015-10-20/obi_core.owl

- path: /obo/obi/obi_IEDBview.owl
  replacement: http://svn.code.sf.net/p/obi/code/releases/2015-10-20/obi_iedb.owl

- path: /obo/obi/release-notes.html
  replacement: http://obi-ontology.org/page/Releases/2015-10-20

- path: /obo/obi/webService.owl
  replacement: https://raw.githubusercontent.com/obi-webservice/OBIws/master/ontology/release/v1.1/webService.owl

- path: /obo/obi/NIAID-GSC-BRC.owl
  replacement: http://svn.code.sf.net/p/obi/code/releases/NIAID-GSCID-BRC-view/20150413/NIAID-GSC-BRC.owl

- path: /obo/obi/obi_FGED.owl
  replacement: http://svn.code.sf.net/p/obi/code/releases/2013-10-25/obi_FGED.owl

# TODO: This is out of date and in the wrong place.
- path: /obo/obi/obi.obo
  replacement: http://obi.svn.sourceforge.net/svnroot/obi/releases/2012-07-01/merged/obi_cleaned_merged_inferred.obo

### Dated OBI Releases

- path: /obo/obi/2009-11-02/obi.owl
  replacement: http://obi.svn.sourceforge.net/svnroot/obi/releases/2009-11-02/merged/merged-obi.owl

- path: /obo/obi/2009-11-06/obi.owl
  replacement: http://obi.svn.sourceforge.net/svnroot/obi/releases/2009-11-06/merged/merged-obi.owl

- path: /obo/obi/2009-11-06/obi.obo
  replacement: http://obi.svn.sourceforge.net/svnroot/obi/releases/2009-11-06/merged/obi.obo

- path: /obo/obi/2009-11-06/IEDB-use-case.owl
  replacement: http://obi.svn.sourceforge.net/svnroot/obi/releases/2009-11-06/branches/IEDB-use-case.owl

- path: /obo/obi/2009-11-06/investigation-use-case.owl
  replacement: http://obi.svn.sourceforge.net/svnroot/obi/releases/2009-11-06/branches/investigation-use-case.owl

- path: /obo/obi/2010-10-26/obi.owl
  replacement: http://obi.svn.sourceforge.net/svnroot/obi/releases/2010-10-26/merged/merged-obi.owl

- path: /obo/obi/2011-04-20/obi.owl
  replacement: http://obi.svn.sourceforge.net/svnroot/obi/releases/2011-04-20/merged/merged-obi-comments.owl

- path: /obo/obi/2011-07-20/obi.owl
  replacement: http://obi.svn.sourceforge.net/svnroot/obi/releases/2011-07-20/merged/merged-obi-comments.owl

- path: /obo/obi/2011-12-13/obi.owl
  replacement: http://obi.svn.sourceforge.net/svnroot/obi/releases/2012-01-18/merged/obi_woIEDB_comments.owl

- path: /obo/obi/2011-12-13/obi_IEDBview.owl
  replacement: http://obi.svn.sourceforge.net/svnroot/obi/releases/2012-01-18/merged/obi_IEDBview.owl

- path: /obo/obi/2012-03-29/obi.owl
  replacement: http://obi.svn.sourceforge.net/svnroot/obi/releases/2012-03-29/merged/merged-obi-comments.owl

- path: /obo/obi/2012-03-29/obi_IEDBview.owl
  replacement: http://obi.svn.sourceforge.net/svnroot/obi/releases/2012-03-29/merged/obi_IEDBview.owl

- path: /obo/obi/2012-03-29/obi.obo
  replacement: http://obi.svn.sourceforge.net/svnroot/obi/releases/2012-03-29/merged/merged-all_mod.obo

- path: /obo/obi/2012-07-01/obi.owl
  replacement: http://obi.svn.sourceforge.net/svnroot/obi/releases/2012-07-01/merged/merged-obi-comments.owl

- path: /obo/obi/2012-07-01/obi.obo
  replacement: http://obi.svn.sourceforge.net/svnroot/obi/releases/2012-07-01/merged/obi_cleaned_merged_inferred.obo

- path: /obo/obi/2013-10-25/obi_core.owl
  replacement: http://svn.code.sf.net/p/obi/code/releases/2013-10-25/obi_core.owl

- path: /obo/obi/2013-10-25/obi.owl
  replacement: http://svn.code.sf.net/p/obi/code/releases/2013-10-25/obi.owl

- path: /obo/obi/2014-03-29/obi.owl
  replacement: http://svn.code.sf.net/p/obi/code/releases/2014-03-29/obi.owl

- path: /obo/obi/2014-03-29/obi_core.owl
  replacement: http://svn.code.sf.net/p/obi/code/releases/2014-03-29/obi_core.owl

- path: /obo/obi/2014-08-18/obi.owl
  replacement: http://svn.code.sf.net/p/obi/code/releases/2014-08-18/obi.owl

- path: /obo/obi/2014-08-18/obi_core.owl
  replacement: http://svn.code.sf.net/p/obi/code/releases/2014-08-18/obi_core.owl

- path: /obo/obi/2014-12-03/obi.owl
  replacement: http://svn.code.sf.net/p/obi/code/releases/2014-12-03/obi.owl

- path: /obo/obi/2014-12-03/obi_core.owl
  replacement: http://svn.code.sf.net/p/obi/code/releases/2014-12-03/obi_core.owl

- path: /obo/obi/2015-03-17/obi.owl
  replacement: http://svn.code.sf.net/p/obi/code/releases/2015-03-17/obi.owl

- path: /obo/obi/2015-03-17/obi_core.owl
  replacement: http://svn.code.sf.net/p/obi/code/releases/2015-03-17/obi_core.owl

- path: /obo/obi/2015-04-13/obi.owl
  replacement: http://svn.code.sf.net/p/obi/code/releases/2015-04-13/obi.owl

- path: /obo/obi/2015-04-13/obi_core.owl
  replacement: http://svn.code.sf.net/p/obi/code/releases/2015-04-13/obi_core.owl

- path: /obo/obi/2015-09-15/obi.owl
  replacement: http://svn.code.sf.net/p/obi/code/releases/2015-09-15/obi.owl

- path: /obo/obi/2015-09-15/obi_core.owl
  replacement: http://svn.code.sf.net/p/obi/code/releases/2015-09-15/obi_core.owl

- path: /obo/obi/2015-10-20/obi.owl
  replacement: http://svn.code.sf.net/p/obi/code/releases/2015-10-20/obi.owl

- path: /obo/obi/2015-10-20/obi_core.owl
  replacement: http://svn.code.sf.net/p/obi/code/releases/2015-10-20/obi_core.owl

### Web Service Releases

- path: /obo/obi/v1.1/webService.owl
  replacement: https://raw.githubusercontent.com/obi-webservice/OBIws/master/ontology/release/v1.1/webService.owl

- path: /obo/obi/v1.0/webService.owl
  replacement: https://raw.githubusercontent.com/obi-webservice/OBIws/master/ontology/release/v1.0/webService.owl

- path: /obo/obi/v0.9/webService.owl
  replacement: https://raw.githubusercontent.com/obi-webservice/OBIws/master/ontology/release/v0.9/webService.owl

# NIAID-GSC-BRC Releases

- path: /obo/obi/20140106/NIAID-GSC-BRC.owl
  replacement: http://svn.code.sf.net/p/obi/code/releases/NIAID-GSCID-BRC-view/20140105/NIAID-GSC-BRC.owl

- path: /obo/obi/20150413/NIAID-GSC-BRC.owl
  replacement: http://svn.code.sf.net/p/obi/code/releases/NIAID-GSCID-BRC-view/20150413/NIAID-GSC-BRC.owl

### Wiki Pages

- path: /obo/obi/wiki
  replacement: http://obi-ontology.org

- path: /obo/obi/wiki/MinimalMetadata
  replacement: http://obi-ontology.org/page/OBI_Minimal_metadata

- prefix: /obo/obi/wiki/
  replacement: http://obi-ontology.org/page/

### Documentation Pages and Redirects

- path: /obo/obi/homepage
  replacement: http://obi-ontology.org/

- prefix: /obo/obi/about/
  replacement: http://www.ontobee.org/browser/rdf.php?o=OBI&iri=http://purl.obolibrary.org/obo/

- prefix: /obo/obi/doc/
  replacement: http://obi.svn.sourceforge.net/svnroot/obi/trunk/docs/

- path: /obo/obi/tracker
  replacement: http://sourceforge.net/tracker/?group_id=177891&atid=886178

- path: /obo/obi/project
  replacement: http://sw.neurocommons.org/obi-303/project.rdf

- path: /obo/obi/calendar
  replacement: http://www.google.com/calendar/embed?src=p8auq0a930und9nugj44p988e4%40group.calendar.google.com&ctz=America/New_York

- path: /obo/obi/jowl
  replacement: http://jowl.ontologyonline.org/obi.html

- path: /obo/obi/policy/metadata
  replacement: http://obi-ontology.org/page/OBI_Minimal_metadata

- path: /obo/obi/Technical_Reports
  replacement: http://obi-ontology.org/page/Technical_Reports

- path: /obo/obi/supplementary/protege-qtt-2009.zip
  replacement: http://www.stanford.edu/~sunid/OBI/Protege_3.4.2.zip

- path: /obo/obi/report.html
  replacement: http://obi.svn.sourceforge.net/svnroot/obi/releases/2010-10-26/merged/newClasses.html

- path: /obo/obi/protege/obi.pprj
  replacement: http://obi.svn.sourceforge.net/svnroot/obi/releases/obsolete-protege-message.html

- path: /obo/obi/protege/obi.owl
  replacement: http://obi.svn.sourceforge.net/svnroot/obi/releases/obsolete-protege-message.html

- path: /obo/obi/owldoc
  replacement: http://owl.cs.manchester.ac.uk/browser/classes/830966544/?session=12cbe539878-8862-12cbe54e7be

- prefix: /obo/obi/protege/
  replacement: http://obi.svn.sourceforge.net/svnroot/obi/releases/2008-11-28/merged/protege/

- path: /obo/obi/browse
  replacement: http://www.ontobee.org/browser/index.php?o=OBI

- prefix: /obo/obi/page/
  replacement: http://www.ontobee.org/browser/rdf.php?o=OBI&iri=

### Development Pages and Redirects

- prefix: /obo/obi/dev/import/
  replacement: http://svn.code.sf.net/p/obi/code/trunk/src/ontology/branches/OntoFox_outputs/

- prefix: /obo/obi/branches/
  replacement: http://obi.svn.sourceforge.net/svnroot/obi/trunk/src/ontology/branches/

- path: /obo/obi/repository
  replacement: http://sourceforge.net/p/obi/code/HEAD/tree/

- prefix: /obo/obi/repository/
  replacement: http://obi.svn.sourceforge.net/svnroot/obi/

# WARN: This entry matches everything under /obo/obi/*! It must be last on the list.
- prefix: /obo/obi/
  replacement: http://obi.svn.sourceforge.net/svnroot/obi/trunk/src/ontology/branches/
