# PURL configuration for http://purl.obolibrary.org/obo/ogms

idspace: OGMS
base_url: /obo/ogms

base_redirect: http://code.google.com/p/ogms/?

products:
- ogms.owl: https://raw.githubusercontent.com/OGMS/ogms/master/src/ontology/ogms.owl

term_browser: ontobee
example_terms:
- OGMS_0000031

entries:

- prefix: /about/
  replacement: http://www.ontobee.org/browser/rdf.php?o=OGMS&iri=http://purl.obolibrary.org/obo/
  tests:
  - from: /about/OGMS_0000031
    to: http://www.ontobee.org/browser/rdf.php?o=OGMS&iri=http://purl.obolibrary.org/obo/OGMS_0000031

- prefix: /
  replacement: http://www.ontobee.org/browser/rdf.php?o=OGMS&iri=http://purl.obolibrary.org/obo/

