# PURL configuration for http://purl.obolibrary.org/obo/ontoneo/

idspace: ONTONEO
base_url: /obo/ontoneo

products:
- ontoneo.owl: https://raw.githubusercontent.com/ontoneo-project/Ontoneo/master/ontoneo.owl

term_browser: ontobee
example_terms:
- ONTONEO_00000005

entries:

### Project Page and Tracker
- exact: /project
  replacement: https://github.com/ontoneo-project/Ontoneo
 
- exact: /tracker
  replacement: https://github.com/ontoneo-project/Ontoneo/issues

### Imported ontologies current release
- exact: /external
  replacement: https://github.com/ontoneo-project/Ontoneo/tree/master/import

### Previous release

- exact: /release/
  replacement: https://github.com/ontoneo-project/Ontoneo/tree/master/releases
  
- exact: /releases/v1
  replacement: https://github.com/ontoneo-project/Ontoneo/tree/master/releases/v1.0
 
- exact: /releases/v1.1
  replacement: https://github.com/ontoneo-project/Ontoneo/tree/master/releases/v1.1
  
### Documentation Pages and Redirects
- exact: /homepage
  replacement: http://ontoneo.com
