# PURL configuration for http://purl.obolibrary.org/obo/ovae

id: OVAE
base_url: /obo/ovae

products:
- ovae.owl: http://ovae.googlecode.com/svn/trunk/src/ontology/ovae.owl

term_browser: ontobee
example_terms:
- OVAE_0000004
