# PURL configuration for http://purl.obolibrary.org/obo/pdumdv

id: PDUMDV
base_url: /obo/pdumdv

products:
- pdumdv.owl: http://www.berkeleybop.org/ontologies/pdumdv.owl
- pdumdv.obo: http://www.berkeleybop.org/ontologies/pdumdv.obo

term_browser: ontobee
example_terms:
- PDUMDV_0001600
