# PURL configuration for http://purl.obolibrary.org/obo/poro

idspace: PORO
base_url: /obo/poro

base_redirect: https://github.com/obophenotype/porifera-ontology

products:
- poro.owl: https://raw.githubusercontent.com/obophenotype/porifera-ontology/master/poro.owl
- poro.obo: https://raw.githubusercontent.com/obophenotype/porifera-ontology/master/poro.obo

term_browser: ontobee
example_terms:
- PORO_0000000

entries:
- exact: /browse
  replacement: http://www.ontobee.org/browser/index.php?o=PORO

- prefix: /releases/
  replacement: https://raw.githubusercontent.com/obophenotype/porifera-ontology/v

- prefix: /about/
  replacement: http://www.ontobee.org/browser/rdf.php?o=PORO&iri=http://purl.obolibrary.org/obo/
  tests:
  - from: /about/PORO_0000000
    to: http://www.ontobee.org/browser/rdf.php?o=PORO&iri=http://purl.obolibrary.org/obo/PORO_0000000

- prefix: /
  replacement: https://raw.githubusercontent.com/obophenotype/porifera-ontology/master/

