# PURL configuration for http://purl.obolibrary.org/obo/pr
# Warning: the Protein Ontology also uses /obo/pro

idspace: PR
base_url: /obo/pr

base_redirect: http://proconsortium.org

products:
- pr.owl: https://research.bioinformatics.udel.edu/PRO/data/current/pro_reasoned.owl
- pr.obo: https://research.bioinformatics.udel.edu/PRO/data/current/pro_reasoned.obo
- pr-asserted.owl: https://research.bioinformatics.udel.edu/PRO/data/current/pro_nonreasoned.owl
- pr-asserted.obo: https://research.bioinformatics.udel.edu/PRO/data/current/pro_nonreasoned.obo

term_browser: custom

entries:

##### PURLs using major.minor style to indicate the release #####
# major releases prior to release 43.0; no reasoned version produced so default to non-reasoned; no OWL produced
# The regex matches three sets of version numbers:
# - 0-9: \d
# - 10-39: [1-3]\d
# - 40-42: 4[0-2]\d
# Then 'pr' and 'pr-asserted' are treated the same.

- regex: (?i)^/obo/pr/((\d|[1-3]\d|4[0-2])\.\d)\.?/(pr|pr-asserted).obo$
  replacement: https://research.bioinformatics.udel.edu/PRO/data/release_$1/pro_nonreasoned.obo
  tests:
  - from: /9.0/pr.obo
    to: https://research.bioinformatics.udel.edu/PRO/data/release_9.0/pro_nonreasoned.obo
  - from: /22.0/pr.obo
    to: https://research.bioinformatics.udel.edu/PRO/data/release_22.0/pro_nonreasoned.obo
  - from: /42.0/pr.obo
    to: https://research.bioinformatics.udel.edu/PRO/data/release_42.0/pro_nonreasoned.obo
  - from: /9.0/pr-asserted.obo
    to: https://research.bioinformatics.udel.edu/PRO/data/release_9.0/pro_nonreasoned.obo
  - from: /22.0/pr-asserted.obo
    to: https://research.bioinformatics.udel.edu/PRO/data/release_22.0/pro_nonreasoned.obo
  - from: /42.0/pr-asserted.obo
    to: https://research.bioinformatics.udel.edu/PRO/data/release_42.0/pro_nonreasoned.obo

# major releases 43.0 and later; reasoned version of both OBO and OWL produced
# The regex matches three sets of version numbers:
# - 43-49: 4[3-9]\d
# - 50-99: [5-9]\d
# - 100-999: \d\d\d
# The file extension can be either 'obo' or 'owl'.

- regex: (?i)^/obo/pr/((4[3-9]|[5-9]\d|\d\d\d)\.\d+)\.?/pr.(obo|owl)$
  replacement: https://research.bioinformatics.udel.edu/PRO/data/release_$1/pro_reasoned.$3
  tests:
  - from: /45.0/pr.obo
    to: https://research.bioinformatics.udel.edu/PRO/data/release_45.0/pro_reasoned.obo
  - from: /45.0./pr.obo
    to: https://research.bioinformatics.udel.edu/PRO/data/release_45.0/pro_reasoned.obo
  - from: /51.0/pr.obo
    to: https://research.bioinformatics.udel.edu/PRO/data/release_51.0/pro_reasoned.obo
  - from: /51.0./pr.obo
    to: https://research.bioinformatics.udel.edu/PRO/data/release_51.0/pro_reasoned.obo
  - from: /45.0/pr.owl
    to: https://research.bioinformatics.udel.edu/PRO/data/release_45.0/pro_reasoned.owl
  - from: /45.0./pr.owl
    to: https://research.bioinformatics.udel.edu/PRO/data/release_45.0/pro_reasoned.owl
  - from: /51.0/pr.owl
    to: https://research.bioinformatics.udel.edu/PRO/data/release_51.0/pro_reasoned.owl
  - from: /51.0./pr.owl
    to: https://research.bioinformatics.udel.edu/PRO/data/release_51.0/pro_reasoned.owl

- regex: (?i)^/obo/pr/((4[3-9]|[5-9]\d|\d\d\d)\.\d+)\.?/pr-asserted.(obo|owl)$
  replacement: https://research.bioinformatics.udel.edu/PRO/data/release_$1/pro_nonreasoned.$3
  tests:
  - from: /45.0/pr-asserted.obo
    to: https://research.bioinformatics.udel.edu/PRO/data/release_45.0/pro_nonreasoned.obo
  - from: /45.0./pr-asserted.obo
    to: https://research.bioinformatics.udel.edu/PRO/data/release_45.0/pro_nonreasoned.obo
  - from: /51.0/pr-asserted.obo
    to: https://research.bioinformatics.udel.edu/PRO/data/release_51.0/pro_nonreasoned.obo
  - from: /51.0./pr-asserted.obo
    to: https://research.bioinformatics.udel.edu/PRO/data/release_51.0/pro_nonreasoned.obo
  - from: /45.0/pr-asserted.owl
    to: https://research.bioinformatics.udel.edu/PRO/data/release_45.0/pro_nonreasoned.owl
  - from: /45.0./pr-asserted.owl
    to: https://research.bioinformatics.udel.edu/PRO/data/release_45.0/pro_nonreasoned.owl
  - from: /51.0/pr-asserted.owl
    to: https://research.bioinformatics.udel.edu/PRO/data/release_51.0/pro_nonreasoned.owl
  - from: /51.0./pr-asserted.owl
    to: https://research.bioinformatics.udel.edu/PRO/data/release_51.0/pro_nonreasoned.owl

# Note that both of the above forms (with and without period after version number) should resolve to the
#   same file, as the extraneous trailing period stems from an error on the data-version line
#   in releases prior to 54.0

### OBO Foundry ID-policy compliant PURLs

- prefix: /about/
  replacement: http://research.bioinformatics.udel.edu/pro/entry/
  tests:
  - from: /about/PR_000000001
    to: http://research.bioinformatics.udel.edu/pro/entry/PR_000000001

- exact: /pr-asserted.obo
  replacement: https://research.bioinformatics.udel.edu/PRO/data/current/pro_nonreasoned.obo
  
- exact: /pr-asserted.owl
  replacement: https://research.bioinformatics.udel.edu/PRO/data/current/pro_nonreasoned.owl
  
- exact: /homepage
  replacement: http://proconsortium.org

- exact: /tracker
  replacement: http://sourceforge.net/tracker/?group_id=266825&atid=1135711

- prefix: /wiki/
  replacement: https://pir17.georgetown.edu/confluence/display/PROWIKI/
  tests:
  - from: /wiki/PRO+PURLs
    to: https://pir17.georgetown.edu/confluence/display/PROWIKI/PRO+PURLs

- exact: /wiki
  replacement: https://pir17.georgetown.edu/confluence/display/PROWIKI

- exact: /browse
  replacement: http://www.ontobee.org/browser/index.php?o=pr

### Development Pages and Redirects

- exact: /pr-dev.obo
  replacement: http://pir.georgetown.edu/projects/pro/pro_wv.obo
