# PURL configuration for http://purl.obolibrary.org/obo/pr
# Warning: the Protein Ontology also uses /obo/pro

idspace: PR
base_url: /obo/pr

base_redirect: http://proconsortium.org

products:
- pr.owl: ftp://ftp.proconsortium.org/databases/ontology/pro_obo/pro_reasoned.owl
- pr.obo: ftp://ftp.proconsortium.org/databases/ontology/pro_obo/pro_reasoned.obo
- pr-asserted.owl: ftp://ftp.proconsortium.org/databases/ontology/pro_obo/pro_nonreasoned.owl
- pr-asserted.obo: ftp://ftp.proconsortium.org/databases/ontology/pro_obo/pro_nonreasoned.obo

term_browser: custom

entries:
- prefix: /release/
  replacement: ftp://ftp.proconsortium.org/databases/ontology/pro_obo/old_files/release_
  tests:
  - from: /release/52.0/pr.obo
    to: ftp://ftp.proconsortium.org/databases/ontology/pro_obo/old_files/release_52.0/pro_reasoned.obo

- prefix: /about/
  replacement: http://research.bioinformatics.udel.edu/pro/entry/
  tests:
  - from: /about/PR_000000001
    to: http://research.bioinformatics.udel.edu/pro/entry/PR_000000001

# ISSUES
# http://purl.obolibrary.org/obo/pr-asserted.obo
#  resolves to
# ftp://ftp.proconsortium.org/databases/ontology/pro_obo/pro.obo
# which is invalid (as is using /pr after obo)
# Also need to ensure versions with trailing period resolve

