# PURL configuration for http://purl.obolibrary.org/obo/pw

id: PW
base_url: /obo/pw

products:
- pw.owl: http://www.berkeleybop.org/ontologies/pw.owl
- pw.obo: http://www.berkeleybop.org/ontologies/pw.obo

term_browser: ontobee
example_terms:
- PW_0000555
