# PURL configuration for http://purl.obolibrary.org/obo/rxno

id: RXNO
base_url: /obo/rxno

products:
- rxno.owl: http://rxno.googlecode.com/svn/trunk/rxno.owl
- rxno.obo: http://rxno.googlecode.com/svn/trunk/rxno.obo

term_browser: ontobee
example_terms:
- RXNO_0000000
