# PURL configuration for http://purl.obolibrary.org/obo/symp

idspace: SYMP
base_url: /obo/symp

products:
- symp.owl: http://ontologies.berkeleybop.org/symp.owl
- symp.obo: http://ontologies.berkeleybop.org/symp.obo

term_browser: ontobee
example_terms:
- SYMP_0000000
