# PURL configuration for http://purl.obolibrary.org/obo/tgma

idspace: TGMA
base_url: /obo/tgma

products:
- tgma.owl: http://www.berkeleybop.org/ontologies/tgma.owl
- tgma.obo: http://www.berkeleybop.org/ontologies/tgma.obo

term_browser: ontobee
example_terms:
- TGMA_0000000
