# PURL configuration for http://purl.obolibrary.org/obo/trans

idspace: TRANS
base_url: /obo/trans

products:
- trans.owl: http://www.berkeleybop.org/ontologies/trans.owl
- trans.obo: http://www.berkeleybop.org/ontologies/trans.obo

term_browser: ontobee
example_terms:
- TRANS_0000000
