# PURL configuration for http://purl.obolibrary.org/obo/trans

idspace: TRANS
base_url: /obo/trans

products:
- trans.owl: http://ontologies.berkeleybop.org/trans.owl
- trans.obo: http://ontologies.berkeleybop.org/trans.obo

term_browser: ontobee
example_terms:
- TRANS_0000000
