# PURL configuration for http://purl.obolibrary.org/obo/tto

idspace: TTO
base_url: /obo/tto

products:
- tto.owl: http://www.berkeleybop.org/ontologies/tto.owl
- tto.obo: http://www.berkeleybop.org/ontologies/tto.obo

term_browser: ontobee
example_terms:
- TTO_201
