# PURL configuration for http://purl.obolibrary.org/obo/vt

idspace: VT
base_url: /obo/vt

products:
- vt.owl: http://ontologies.berkeleybop.org/vt.owl
- vt.obo: http://ontologies.berkeleybop.org/vt.obo

term_browser: ontobee
example_terms:
- VT_0000001

entries:
- prefix: /avout/
  replacement: http://www.ontobee.org/browser/rdf.php?o=OBA&iri=http://purl.obolibrary.org/obo/

- prefix: /about/
  replacement: http://www.ontobee.org/browser/rdf.php?o=OBA&iri=http://purl.obolibrary.org/obo/
  tests:
  - from: /about/VT_0000001
    to: http://www.ontobee.org/browser/rdf.php?o=OBA&iri=http://purl.obolibrary.org/obo/VT_0000001
