# PURL configuration for http://purl.obolibrary.org/obo/wbphenotype

idspace: WBPhenotype
base_url: /obo/wbphenotype

products:
- wbphenotype.owl: http://www.berkeleybop.org/ontologies/wbphenotype.owl
- wbphenotype.obo: http://www.berkeleybop.org/ontologies/wbphenotype.obo

term_browser: ontobee
example_terms:
- WBPhenotype_0000886

