####
#### Use kwalify and this schema to validate the config files.
#### Example:
####    kwalify -E -m cofig.schema.yaml
####    kwalify -E -f ./metadata/db-xrefs.schema.yaml ./metadata/db-xrefs.yaml
####
type: map
mapping:
  "purl_rules":
    type: seq
    sequence:
      - type: map
        mapping:
          "path":
            type: str
            pattern: /^\//
            unique: true
          "prefix":
            type: str
            pattern: /^\//
            unique: true
          "regex":
            type: str
            unique: true
          "term_browser":
            type: str
            pattern: /^(ontobee)$/
            unique: true
          "replacement":
            type: str
            pattern: /^(https?|ftp)\:\/\/.+|\/obo\//
          "level":
            type: str
            pattern: /^(project|top)$/
          "status":
            type: str
            pattern: /^(permanent|temporary|see other)$/
          "tests":
            type: seq
            sequence:
              - type: map
                mapping:
                  "path":
                    type: str
                    pattern: /^\//
                    required: true
                  "replacement":
                    type: str
                    pattern: /^(https?|ftp)\:\/\/.+|\/obo\//
                    required: true
